### ISSUE TITLE
adding  "Carryable" to any block

### ISSUE THREAD

**Issue by radiocrack** [copygirl/CarryCapacity#1]
Hi Copygirl, Elwood here

Not an issue but a question

I was looking at how you patched chests and baskets.  Can the "Carryable" attribute be added to any block or just containers?

I was thinking I could add the attribute to the carcass block in my animal products mod.  Then carry the carcass on my back.

I would need to somehow use the jsonpatch "test" to make sure the CarryCapacity mod is loaded.  Then i could use patch to add the Carryable attribute optionally to my carcass block.

**Comment by copygirl** [comment]
You **can** add the behavior that allows picking up a block to any block. In fact, if I disable the behavior requirement, you can pick up grass, loose stones, even water!

You already saw my [`carryable.json`](https://github.com/copygirl/CarryCapacity/blob/master/resources/assets/carrycapacity/patches/carryable.json) patch, but I figure I'll mention it for anyone else seeing this issue. The behavior name doesn't use a domain so don't use `"carrycapacity:Carryable"`.

I think you are correct in that a `test` operation checking whether `/behaviors/0/name` for the chest or basket is `"Carryable"` should do what you want, but I'm a little worried the JsonPatch library didn't do this correctly... again.
