### ISSUE TITLE
Support-dependent block doesn't fall (with Better Crates mod?)

### ISSUE THREAD

**Issue by Craluminum2413** [copygirl/CarryCapacity#11]
Support-dependent block doesn't fall if support carriable block like Better Crate under that block is carried. I noticed that bug with brass torch holders and planters, but I'm sure that the same happens with the rest of the blocks that need support block
![2021-04-05_22-39-40](https://user-images.githubusercontent.com/69315569/113619496-b8b81d00-9661-11eb-9920-fd56704a801b.png)

**Comment by copygirl** [comment]
Ah yes, that's right. Carrying blocks does not cause a block update.
