### ISSUE TITLE
Stopped working from VS 1.15.0-pre.10 upwards

### ISSUE THREAD

**Issue by phellmes** [copygirl/CarryCapacity#12]
I can't pick up and carry items anymore with the new 1.15 preview versions from pre.10 on. It works fine up until pre.9.
I use CarryCapacity v0.6.1.

**Comment by copygirl** [comment]
I've been looking into this but it seems more complicated than I thought / was hoping for.

- The mod loads correctly.
- All patches are applied successfully.
- Some blocks *can* be carried.
- The blocks that can't appear to be missing the `Carryable` behavior.

**Comment by phellmes** [comment]
Thanks for the details, I hope you'll find a solution. Meanwhile I stay on pre.9... the mod has become essential to my play style. Great work so far!
If I can supply you with any helpful information, just tell me and I'll look into it.

**Comment by phellmes** [comment]
I quickly checked for chests - the asset path has changed from pre9 to pre10 (now in wood instead of wood/generic) so your carryable.json patch file has the wrong path. Is it that simple?

**Comment by phellmes** [comment]
Yep, looks like it. I unpacked the mod, changed the path for chests and barrels in carryable.json, repacked and now I can pick them up again in pre.11. So I think sudden changes to asset paths or their file structures should be communicated more verbose in the dev notes since they will clearly break patches and maybe other overrides in mods.

**Comment by copygirl** [comment]
That's strange. I checked the logs and it said all patches were applied.

**Comment by copygirl** [comment]
Fixed in [v0.6.2](https://github.com/copygirl/CarryCapacity/releases/tag/v0.6.2). Thank you very much for the help!

**Comment by phellmes** [comment]
Yeah, should at least give a warning if a patch path points nowhere...
Thanks for fixing!

**Comment by copygirl** [comment]
It does give a warning: "Missing files on 4 patches" or something along those lines. But I think I was looking at the incorrect log file.
