### ISSUE TITLE
Allow to carry clay molds (useful for filled ones)

### ISSUE THREAD

**Issue by Craluminum2413** [copygirl/CarryCapacity#15]
```json
  {
    "op": "add",
    "path": "/behaviorsByType/*/1",
    "value": {
      "name": "Carryable",
      "properties": {
        "translation": [
          0.0625,
          0,
          0
        ],
        "rotation": [
          0,
          180,
          0
        ],
        "slots": {
          "Hands": {},
          "Back": {}
        }
      }
    },
    "file": "blocktypes/clay/mold/ingotmold.json"
  }


  {
    "op": "add",
    "path": "/behaviorsByType/*/1",
    "value": {
      "name": "Carryable",
      "properties": {
        "translation": [
          0.0625,
          0,
          0
        ],
        "rotation": [
          0,
          180,
          0
        ],
        "slots": {
          "Hands": {},
          "Back": {}
        }
      }
    },
    "file": "blocktypes/clay/mold/toolmold.json"
  }
```

**Comment by Craluminum2413** [comment]
![image](https://user-images.githubusercontent.com/69315569/154864609-3a66009d-9a83-43ba-a651-2797e35ee95d.png)

**Comment by Craluminum2413** [comment]
Btw ingot molds get carried as two at once

**Comment by copygirl** [comment]
This is an interesting idea, but when I think about it, the cooling liquid metal should probably not be disturbed as it settles. Cooling is also relatively fast and picking the mold up only pauses this process. So I won't be implementing this. Additionally, it doesn't make sense for (non-anvil) molds to be carryable on one's back.

**Comment by Craluminum2413** [comment]
I noticed it is cooling when carrying

**Comment by copygirl** [comment]
Oh right, I guess it's implemented by remembering when the cooling process started - then the progress can be measured by how much time passed, rather than updating it every single game tick.

**Comment by Craluminum2413** [comment]
I suggested this mostly because in my sp world I have `15/100` ingot mold with tin bronze that I cannot move

**Comment by Craluminum2413** [comment]
If you would like, you can reference this message into a new issue
![image](https://user-images.githubusercontent.com/69315569/154864894-b1d53a47-7ef3-4471-b814-8314b639c0e0.png)

**Comment by copygirl** [comment]
Good point on moving partly filled ingot molds. But still, it's not a good fit, and has some weird effects. Feel free to make it into a separate mod!
