### ISSUE TITLE
(Suggestion) Carryable torch holder and tool racks

### ISSUE THREAD

**Issue by Craluminum2413** [copygirl/CarryCapacity#19]
I picked them up and didn't encountered with errors, so I think it is safe to add

**Comment by copygirl** [comment]
They don't have a good solid bounding box - it wouldn't look good.
Torch holders also can just be picked up without an issue.

**Comment by Craluminum2413** [comment]
What is "solid bounding box"?

**Comment by copygirl** [comment]
Something the player can realistically hold with their hands. The torch holder is much smaller than any other block you can currently pick up, so it would require a custom animation. Tool racks are just two planks attacked to a wall; there's no rotation I can imagine looking good when carried. (You can prove me wrong, but I still don't think these are good choices for adding to the pool of carryable blocks.)

**Comment by Craluminum2413** [comment]
This for tool rack
```json
"translation": [0.0625, 0, 0], "rotation": [0, 90, 90],
```
