### ISSUE TITLE
Not working for older worlds

### ISSUE THREAD

**Issue by prussell84** [copygirl/CarryCapacity#21]
I've found that it doesn't work for my worlds that were created before updating to 1.16.5 including a 1.16.4 world.  It does work if I create a new world just not for any of the older worlds.  I also have removed all other mods to make sure they were not causing a conflict.

**Comment by copygirl** [comment]
Do blocks that are supposed to be carryable have the block interaction hint? (Of course, block interaction hints need to be enabled in the settings.) ~~Could be the bug that [Rhyagelle discovered](https://www.vintagestory.at/forums/topic/320-carrycapacity-v065/?do=findComment&comment=36383) on the forum; something really strange with the mod "Defensive Structures". What's your modlist?~~ In fact, send me your `client-main.txt` and `server-main.txt` in case those shed a light on what's going on.

edit: I wish I could read.

**Comment by prussell84** [comment]
[client-main.txt](https://github.com/copygirl/CarryCapacity/files/8708643/client-main.txt)
[server-main.txt](https://github.com/copygirl/CarryCapacity/files/8708645/server-main.txt)

I do have the block interaction hints on and I do get the hint for how to carry but it just opens and closes the chest when I attempt it.

**Comment by copygirl** [comment]
Attempted to reproduce - wasn't able:

- Downgraded to 1.16.4.
- Created a new world, went into creative mode, placed down chest, basket, barrel.
- Closed the game and upgraded to version 1.16.5 again.
- Joined the world, was able to pick up the previously placed blocks.

**Comment by prussell84** [comment]
I just did the same and was not able to reproduce either.  I tried with versions going back to 1.15.5 and no luck in reproducing the issue.  Only seems to happen with a normal world and creative one I created on 1.16.4 but worlds I'm creating now on 1.16.4 are working on 1.16.5.  I'll poke around a bit and see if I can reproduce it.

**Comment by prussell84** [comment]
It seems to be working now for me, might be from downgrading and upgrading.  This might have just been a one off issue.  Thank you for your quick responses.
